### ISSUE TITLE
Failed to load the flying-art-preview package

### ISSUE THREAD

**Issue by stanwmusic** [ZombieHippie/flying-art-preview#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0-beta0 x64
**Electron**: 2.0.5
**OS**: Ubuntu 14.04.5
**Thrown From**: [flying-art-preview](https://github.com/ZombieHippie/flying-art-preview) package 0.1.20

### Stack Trace

Failed to load the flying-art-preview package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/flying-art-preview/lib/flying-art-preview-view.coffee:3:25)
    at /packages/flying-art-preview/lib/flying-art-preview-view.coffee:1:1)
    at /packages/flying-art-preview/lib/flying-art-preview-view.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom-beta/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/flying-art-preview/lib/flying-art-preview.coffee:4:24)
    at /packages/flying-art-preview/lib/flying-art-preview.coffee:1:1)
    at /packages/flying-art-preview/lib/flying-art-preview.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom-beta/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom-beta/resources/app/src/package.js:782:33)
    at measure (/usr/share/atom-beta/resources/app/src/package.js:143:22)
    at Package.measure (/usr/share/atom-beta/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom-beta/resources/app/src/package.js:129:16)
```

### Commands

```
```

### Non-Core Packages

```
advanced-custom-fields-snippets 1.1.0 
angular-bootstrap 1.0.1 
angular2-snippets 0.4.0 
angularjs 0.5.3 
angularjs-snippets 0.10.18 
atom-bemmet 2.0.0 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-clock 0.1.16 
atom-html-preview 0.2.5 
atom-html-templates 0.1.3 
atom-html-templates-extended 0.3.0 
atom-template-engine 0.2.2 
atom-templatebuilder-tools 0.7.2 
atom-webbrowser 2.1.4 
atom-wordpress 0.3.0 
atom-wp-customizer 0.1.0 
autocomplete-wordpress-hooks 0.2.3 
b-bootstrap-autocomplete 0.4.6 
best-js-snippets 4.1.0 
bootstrap-3-snippets-for-atom 2.17.0 
bootstrap-3-snippetset 0.0.6 
bootstrap-sass-snippets 2.1.1 
bootstrap3-snippets 0.1.2 
bootstrap4-snippets 0.2.2 
busy-signal 1.4.3 
cdn-libs 0.1.3 
copy-word 0.7.1 
css-from-html 0.1.5 
css-snippets 1.1.0 
django-templates 0.5.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
emmet-jsx-props 1.4.0 
emmet-simplified 2.6.0 
emmet-snippets-compatibility 1.0.6 
emmet-snippets-compatibility-but-less-extreme 1.1.0 
export-html 3.1.0 
expressjs 2.2.0 
file-templates 0.2.0 
flying-art-preview 0.1.20 
html-head-snippets 0.2.0 
html-to-css 0.2.2 
HTML2JS 0.2.1 
htmlhint 1.1.4 
impress 0.1.1 
intentions 1.1.5 
irregular-keypress-sounds 0.2.0 
jade 1.2.0 
js-extras 1.13.0 
language-expressionengine 0.2.3 
language-wp 0.1.1 
laravel-forms-bootstrap-snippets 1.2.0 
linter 2.2.0 
linter-bootlint 1.1.0 
linter-ui-default 1.7.1 
livestyle-atom 0.2.10 
local-server-express 0.3.1 
moso-atom-snippets 0.3.0 
open-in-browser 0.5.2 
package-list 0.1.2 
pair-pressure 0.1.3 
pigments 0.40.2 
pinegrow-atom 0.3.1 
rawn-snippets 0.1.5 
scss-snippets 0.6.0 
template-insert 2.1.1 
tornado-templates 0.2.0 
v-bootstrap4 0.2.2 
vim-plus-autocomplete-emmet-compatibility 0.1.0 
webflow-to-wordpress 0.0.2 
wordpress 0.2.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-dictionary 4.4.0 
wordpress-suite 1.3.0 
wp-dev 0.3.5 
```

**Comment by stanwmusic** [comment]
This is No big  deal or worry to me. I only created this issue in case it may help someone else.
